# Generated by Django 4.1 on 2022-08-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=56)),
                ('correo', models.CharField(max_length=56)),
                ('pais', models.CharField(max_length=56)),
                ('status_beca', models.CharField(max_length=56)),
                ('area_estudio', models.CharField(max_length=56)),
                ('area_de_interes', models.CharField(max_length=56)),
            ],
            options={
                'db_table': 'becarios',
            },
        ),
    ]
